# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hl2_forecast.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12hl2_forecast.proto\"\x9a\x04\n\x0cHandForecast\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x17\n\x0fsource_frame_id\x18\x02 \x01(\x04\x12#\n\x1bsource_capture_timestamp_ns\x18\x03 \x01(\x04\x12\x18\n\x10legacy_timestamp\x18\x04 \x01(\x02\x12#\n\x1bserver_receive_timestamp_ns\x18\x05 \x01(\x04\x12$\n\x1cinference_start_timestamp_ns\x18\x06 \x01(\x04\x12\"\n\x1ainference_end_timestamp_ns\x18\x07 \x01(\x04\x12 \n\x18server_send_timestamp_ns\x18\x08 \x01(\x04\x12\r\n\x05valid\x18\t \x01(\x08\x12\x10\n\x08track_id\x18\n \x01(\t\x12\x1f\n\nhandedness\x18\x0b \x01(\x0e\x32\x0b.Handedness\x12*\n\x10\x63oordinate_space\x18\x0c \x01(\x0e\x32\x10.CoordinateSpace\x12\x13\n\x0bhorizons_ms\x18\r \x03(\x02\x12\x12\n\njoints_25d\x18\x0e \x03(\x02\x12\x19\n\x11source_anchor_25d\x18\x0f \x03(\x02\x12&\n\x0einvalid_reason\x18\x10 \x01(\x0e\x32\x0e.InvalidReason\x12\x15\n\rmodel_version\x18\x11 \x01(\t\x12\x16\n\x0ehistory_length\x18\x12 \x01(\r*=\n\nHandedness\x12\x1a\n\x16HANDEDNESS_UNSPECIFIED\x10\x00\x12\x08\n\x04LEFT\x10\x01\x12\t\n\x05RIGHT\x10\x02*7\n\x0f\x43oordinateSpace\x12\x15\n\x11SPACE_UNSPECIFIED\x10\x00\x12\r\n\tIMAGE_25D\x10\x03*\x9c\x01\n\rInvalidReason\x12\x08\n\x04NONE\x10\x00\x12\x10\n\x0cNO_DETECTION\x10\x01\x12\x15\n\x11ROOT_DEPTH_FAILED\x10\x02\x12\x18\n\x14INSUFFICIENT_HISTORY\x10\x03\x12\x0f\n\x0bHISTORY_GAP\x10\x04\x12\x17\n\x13TIMESTAMP_REGRESSED\x10\x05\x12\x14\n\x10TRANSFORM_FAILED\x10\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hl2_forecast_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HANDEDNESS._serialized_start=563
  _HANDEDNESS._serialized_end=624
  _COORDINATESPACE._serialized_start=626
  _COORDINATESPACE._serialized_end=681
  _INVALIDREASON._serialized_start=684
  _INVALIDREASON._serialized_end=840
  _HANDFORECAST._serialized_start=23
  _HANDFORECAST._serialized_end=561
# @@protoc_insertion_point(module_scope)
